---
title: "git_01"
author: "Jasmine Walters"
date: "March 25 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

A boat beneath a sunny sky,  
Lingering onward dreamily  
In an evening of July —  
Children three that nestle near,  
Eager eye and willing ear,
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun." 
## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->
O Captain! my Captain! our fearful trip is done,  
The ship has weather’d every rack, the prize we sought is won,  
The port is near, the bells I hear, the people all exulting,  
While follow eyes the steady keel, the vessel grim and daring;  
                         But O heart! heart! heart!  
                            O the bleeding drops of red,  
                               Where on the deck my Captain lies,  
                                  Fallen cold and dead.  

O Captain! my Captain! rise up and hear the bells;  
Rise up—for you the flag is flung—for you the bugle trills,  
For you bouquets and ribbon’d wreaths—for you the shores a-crowding,  
For you they call, the swaying mass, their eager faces turning;  
                         Here Captain! dear father!  
                            This arm beneath your head!  
                               It is some dream that on the deck,  
                                 You’ve fallen cold and dead.  

My Captain does not answer, his lips are pale and still,  
